openapi: 3.0.0
info:
  title: Otch API
  description: Description of Otch API
  version: 0.0.1
servers:
  - url: https://api.otch.xyz/
    description: Main (production) server

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string

security:
  - basicAuth: []

paths:
  /users/getById:
    get:
      summary: Return user by id.
      description: Return user by id.
      responses:
        '200':
          description: A JSON object with data about user
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/User'
